### Get access token for shop-client
POST http://localhost:3000/realms/shop/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=shop-client&client_secret=VwpcoDqxMdTJDTWJBIEs6aa3W7EvPjZz

### Get access token for shop-admin-client
POST http://localhost:3000/realms/shop/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=shop-admin-client&client_secret=Z4s4D0nbBo6HeLu5p0VSmZsP9bMY6nwE


### Get public info (does not require any token)
GET http://localhost:8080/api/info/public

### Get protected info (requires any valid token)
GET http://localhost:8080/api/info/protected
Authorization: Bearer <token>

### Get admin user info (requires valid token containing admin role)
GET http://localhost:8080/api/info/admin
Authorization: Bearer <token>

