### Get access token for shop-client
POST http://localhost:3000/realms/shop/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=shop-client&client_secret=VwpcoDqxMdTJDTWJBIEs6aa3W7EvPjZz

### Get access token for shop-admin-client
POST http://localhost:3000/realms/shop/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=shop-admin-client&client_secret=Z4s4D0nbBo6HeLu5p0VSmZsP9bMY6nwE


### Get public info (does not require any token)
GET http://localhost:8080/api/info/public

### Get protected info (requires any valid token)
GET http://localhost:8080/api/info/protected
Authorization: Bearer {{$auth.token("shop-client")}}

### Get protected method info (requires any valid token)
GET http://localhost:8080/api/info/protected-method
Authorization: Bearer {{$auth.token("shop-client")}}

### Get admin user info (requires valid token containing admin role)
GET http://localhost:8080/api/info/admin
Authorization: Bearer {{$auth.token("shop-admin-client")}}

### Get product belonging to logged in user
GET http://localhost:8080/api/products/1
Authorization: Bearer {{$auth.token("shop-client")}}

### Get product not belonging to logged in user
GET http://localhost:8080/api/products/2
Authorization: Bearer {{$auth.token("shop-client")}}

### Get product belonging to logged in user (authorization code flow)
GET http://localhost:8080/api/products/3
Authorization: Bearer {{$auth.token("shop-users-client")}}

### Get product not belonging to logged in user (authorization code flow)
GET http://localhost:8080/api/products/4
Authorization: Bearer {{$auth.token("shop-users-client")}}

### Get products for logged in user
GET http://localhost:8080/api/products
Authorization: Bearer {{$auth.token("shop-client")}}

### Get all products (if logged user is admin)
GET http://localhost:8080/api/products
Authorization: Bearer {{$auth.token("shop-admin-client")}}

### Get products owned by logged in user
GET http://localhost:8080/api/products/ownedBy/shop-client
Authorization: Bearer {{$auth.token("shop-client")}}

### Get products not owned by logged in user
GET http://localhost:8080/api/products/ownedBy/shop-admin-client
Authorization: Bearer {{$auth.token("shop-client")}}

### Get products not owned by logged in user (if logged user is admin)
GET http://localhost:8080/api/products/ownedBy/shop-client
Authorization: Bearer {{$auth.token("shop-admin-client")}}
